#############################################################################
#
# Project Makefile
#
# (c) R2D2-leads 2020
#
# This file is in the public domain.
# 
#############################################################################

MODULE_NAME			= humidity-sensor
SERIAL_PORT 		= /dev/tty.usbmodem143201 	#/dev/ttyACM0
												#/dev/tty.usbmodem146201
												#COM4

PLATFORM			= native					#native
												#due


CONSOLE_BAUDRATE	= 115200

export 
include $(R2D2_ROOT_DRIVE)$(R2D2_ROOT_DIR)/modules/Makefile.module